### ISSUE TITLE
Authentication with egress server

### ISSUE THREAD

**Issue by sngc1** [livekit/livekit-server-sdk-python#11]
Hello, thanks for the Python SDK!

Is there any example of sending a request to the Egress server?
I am somehow trying to send TrackEgressRequest after joining a room below, while the server responds `"status": "401", "error": "permissions denied", "code": "unauthenticated"`. 

It is really helpful If there are any guides about how to use the EgressClient, thanks!

```
egress_client = livekit.twirp.EgressClient(address=MY_LIVEKIT_SERVER)

response = egress_client.StartTrackEgress(
    ctx=twirp.context.Context(),
    request=livekit.egress.TrackEgressRequest(
        room_name=MY_ROOM,
        track_id=MY_TRACK,
        websocket_url=MY_WEBSOCKET_SERVER,
    ),
    headers={"Authorization": f"Bearer {MY_TOKEN}"},
)
```

**Comment by davidzhao** [comment]
what permissions have you granted to the token?

**Comment by sngc1** [comment]
Oh I overlooked the `roomRecord` grant is needed to use Egress...
Now the auth works, thanks!
